kind: Service
apiVersion: v1
metadata:
  name: service4
spec:
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 8089
      targetPort: 8999
  selector:
    app: server4
  type: LoadBalancer

status:
  loadBalancer: {}
