kind: Service
apiVersion: v1
metadata:
  name: service-a
spec:
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 8087
      targetPort: 8999
  selector:
    app: service-a
  type: LoadBalancer

status:
  loadBalancer: {}
